// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9j86I0jdRfLk15lljMXgyWwxGPRYiVbo',
    appId: '1:645826096202:web:8d6f983c26c5191a784ab3',
    messagingSenderId: '645826096202',
    projectId: 'todo-app-83d6c',
    authDomain: 'todo-app-83d6c.firebaseapp.com',
    storageBucket: 'todo-app-83d6c.appspot.com',
    measurementId: 'G-30KET7X00S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsKAVyXHjYPwF7CBsD4aZmDACGkzWesfs',
    appId: '1:645826096202:android:07bc3f59794a565b784ab3',
    messagingSenderId: '645826096202',
    projectId: 'todo-app-83d6c',
    storageBucket: 'todo-app-83d6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKRaMhzuIDi7Y79HPYth2lENE2z1dK5eE',
    appId: '1:645826096202:ios:0a726a09de0e1731784ab3',
    messagingSenderId: '645826096202',
    projectId: 'todo-app-83d6c',
    storageBucket: 'todo-app-83d6c.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKRaMhzuIDi7Y79HPYth2lENE2z1dK5eE',
    appId: '1:645826096202:ios:452c7ecaccb306aa784ab3',
    messagingSenderId: '645826096202',
    projectId: 'todo-app-83d6c',
    storageBucket: 'todo-app-83d6c.appspot.com',
    iosBundleId: '4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9j86I0jdRfLk15lljMXgyWwxGPRYiVbo',
    appId: '1:645826096202:web:d8d0ab69e168b068784ab3',
    messagingSenderId: '645826096202',
    projectId: 'todo-app-83d6c',
    authDomain: 'todo-app-83d6c.firebaseapp.com',
    storageBucket: 'todo-app-83d6c.appspot.com',
    measurementId: 'G-BJ4KF96ZM7',
  );
}